"use client";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
import { Space_Grotesk } from "next/font/google";
import { createTheme, ThemeProvider } from "@mui/material/styles";

const spaceGrotesk = Space_Grotesk({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const theme = createTheme({
  typography: {
    fontFamily:
      "Space Grotesk, var(--font-geist-sans), var(--font-geist-mono), sans-serif",
    // "Space Grotesk, var(--font-geist-sans), var(--font-geist-mono), sans-serif",
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className} style={{ margin: "0px" }}>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
